### ISSUE TITLE
please

### ISSUE THREAD

**Issue by yinmengkai** [JinshuChen/MOGAN#2]
I am a graduate student from shanghai university of electric power of in China.
My research is focused on machine learning and deep learning. I have recently read your paper”MOGAN: Morphologic-structure-aware Generative Learning from a Single Image”,which appeared in IEEE. I am very interested in this article and have studied it carefully. I try to run your code.I am wondering if you could kindly send me the code about it. I promise they will be used only for research purposes.
Thank you for your reading, I am looking forward to your early reply.

**Comment by JinshuChen** [comment]
Hi yinmeng, contact me with e-mails chenjinshu@bytedance.com
